server:
  port: 8081
  context-path: /
  
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookSearcher?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: user
    password: 1234
  servlet:
    multipart:
      max-file-size: 1100MB
      max-request-size : 1100MB

elasticsearch:
  host: localhost
  port: 9200
  scheme: http
  
logging:
  level:
    org:
      springframework:
        data:
          elasticsearch: DEBUG
mybatis:
  type-aliases-package: com.core.module
  config-location: classpath:mybatis/config/Mybatis_Config.xml
  mapper-locations: classpath:mybatis/mapper/**/*_MySQL.xml


