server:
  port: 8081
  context-path: /

spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size : 500MB

elasticsearch:
  ip: localhost
  port: 9200
  protocol: http
  rest:
    connection-timeout: 3600000

jwt:
  header: Authorization
  secret: +5YX+OQfSUhJIgTMuhienEaM36BaBhHR4wSSyYf6uwKAre2zEUEK+2CjPMhPKG/e0yaidQwrnTnp8ZlsEm9lFg==
  token-validity-in-seconds: 1800 # (초)

logging:
  level:
    org:
      springframework:
        data:
          elasticsearch: DEBUG